CREATE DATABASE Marketing_Analytics;

CREATE TABLE marketing_data (
    id INT PRIMARY KEY,
    date DATETIME,
    region VARCHAR(20),
    channel VARCHAR(30),
    product_category VARCHAR(50),
    customer_segment VARCHAR(30),

    ad_spend DECIMAL(12,2),
    price DECIMAL(10,2),
    discount_rate DECIMAL(5,2),
    market_reach DECIMAL(10,2),

    impressions INT,
    click_through_rate DECIMAL(6,2),
    competition_index DECIMAL(6,2),
    seasonality_index DECIMAL(6,2),
    campaign_duration_days INT,

    customer_lifetime_value DECIMAL(12,2),
    sales_revenue DECIMAL(12,2)
);











                                 ## MODULE 1

###   Q1:-  How can the Marketing Manager view all campaign records available in the database?

SELECT *
FROM marketing_data;

##  Q2:- What information is available for each marketing campaign?

SELECT
    id,
    date,
    region,
    channel,
    product_category,
    sales_revenue
FROM marketing_data;

## Q3:- What are the different marketing channels used by the company?

SELECT DISTINCT channel
FROM marketing_data;

## Q4:- Which regions does the company operate in?

SELECT DISTINCT region
FROM marketing_data;


## Q5:- Show all campaigns that were conducted in the North region.

SELECT *
FROM marketing_data
WHERE region = 'North';

## Q6:- Which campaigns generated more than ₹50,000 in sales revenue?


SELECT
    id,
    channel,
    sales_revenue
FROM marketing_data
WHERE sales_revenue > 50000;

## Q7:- Which are the top 10 highest revenue campaigns?


SELECT
    id,
    region,
    channel,
    sales_revenue
FROM marketing_data
ORDER BY sales_revenue DESC
LIMIT 10;


                                      ## MODULE 2
                                      
## Q1:- How many marketing campaigns has the company conducted?

SELECT COUNT(*) AS Total_Campaigns
FROM marketing_data;

## Q2:- What is the total sales revenue generated by all campaigns?

SELECT SUM(sales_revenue) AS Total_Revenue
FROM marketing_data;


## Q3:- How much did the company spend on advertising in total?

SELECT SUM(ad_spend) AS Total_Ad_Spend
FROM marketing_data;


## Q4:- What is the average sales revenue per campaign?

SELECT AVG(sales_revenue) AS Average_Revenue
FROM marketing_data;

## Q5:- What are the highest and lowest sales revenues recorded?

SELECT
    MAX(sales_revenue) AS Highest_Revenue,
    MIN(sales_revenue) AS Lowest_Revenue
FROM marketing_data;

## Q6:- How many campaigns were conducted in each region?

SELECT
    region,
    COUNT(*) AS Total_Campaigns
FROM marketing_data
GROUP BY region;

## Q7:- What is the total revenue generated by each marketing channel?

SELECT
    channel,
    SUM(sales_revenue) AS Total_Revenue
FROM marketing_data
GROUP BY channel
ORDER BY Total_Revenue DESC;


## Q8:- Which customer segment generates the highest average Customer Lifetime Value (CLV)?

SELECT
    customer_segment,
    AVG(customer_lifetime_value) AS Average_CLV
FROM marketing_data
GROUP BY customer_segment
ORDER BY Average_CLV DESC;


## Q9:- Which product categories generated more than ₹50 million in revenue?

SELECT
    product_category,
    SUM(sales_revenue) AS Total_Revenue
FROM marketing_data
GROUP BY product_category
HAVING SUM(sales_revenue) > 50000000;

## Q10:- Which region has the highest average ad spend?

SELECT
    region,
    AVG(ad_spend) AS Average_Ad_Spend
FROM marketing_data
GROUP BY region
ORDER BY Average_Ad_Spend DESC;


                               ## MODULE 3
                               
  ## Q1:- Which campaigns generated sales revenue between ₹30,000 and ₹50,000?
  
  SELECT
    id,
    channel,
    region,
    sales_revenue
FROM marketing_data
WHERE sales_revenue BETWEEN 30000 AND 50000;

## Q2:- Show campaigns that were conducted in the North and South regions only.

SELECT
    id,
    region,
    channel,
    sales_revenue
FROM marketing_data
WHERE region IN ('North', 'South');


## Q3:-   Find all marketing channels that contain the word "Social".

SELECT DISTINCT channel
FROM marketing_data
WHERE channel LIKE '%Social%';

## Q4:- Are there any campaigns where Customer Lifetime Value is missing?

SELECT *
FROM marketing_data
WHERE customer_lifetime_value IS NULL;

## Q5:-  Classify campaigns based on sales revenue.


SELECT
    id,
    sales_revenue,
    CASE
        WHEN sales_revenue >= 80000 THEN 'High Revenue'
        WHEN sales_revenue >= 50000 THEN 'Medium Revenue'
        ELSE 'Low Revenue'
    END AS Revenue_Category
FROM marketing_data;


## Q6:- Categorize campaigns based on advertising spend.

SELECT
    id,
    ad_spend,
    CASE
        WHEN ad_spend >= 8000 THEN 'High Budget'
        WHEN ad_spend >= 4000 THEN 'Medium Budget'
        ELSE 'Low Budget'
    END AS Budget_Category
FROM marketing_data;


## Q7:-  Find all Email and Social Media campaigns that generated more than ₹60,000 in sales.

SELECT
    id,
    channel,
    sales_revenue
FROM marketing_data
WHERE channel IN ('Email', 'Social Media')
AND sales_revenue > 60000;

## Q8:- Which campaigns ran for more than 20 days and achieved a click-through rate above 5%?

SELECT
    id,
    campaign_duration_days,
    click_through_rate
FROM marketing_data
WHERE campaign_duration_days > 20
AND click_through_rate > 5;



## Q9:- Classify customer lifetime value into Premium, Standard, and Basic customers.

SELECT
    customer_segment,
    customer_lifetime_value,
    CASE
        WHEN customer_lifetime_value >= 15000 THEN 'Premium'
        WHEN customer_lifetime_value >= 8000 THEN 'Standard'
        ELSE 'Basic'
    END AS Customer_Category
FROM marketing_data;


## Q10:- Display only campaigns whose product category starts with the word "Elect".

SELECT
    id,
    product_category,
    sales_revenue
FROM marketing_data
WHERE product_category LIKE 'Elect%';

 
 
                            ## MODULE 4
                            
  ## Q1:- Which campaigns generated more revenue than the average campaign revenue?
  
  SELECT
    id,
    channel,
    sales_revenue
FROM marketing_data
WHERE sales_revenue >
(
    SELECT AVG(sales_revenue)
    FROM marketing_data
);

## Q2:- Which campaigns have an ad spend greater than the average ad spend?


SELECT
    id,
    channel,
    ad_spend
FROM marketing_data
WHERE ad_spend >
(
    SELECT AVG(ad_spend)
    FROM marketing_data
);

## Q3:- Which campaigns belong to the highest revenue channel?

SELECT *
FROM marketing_data
WHERE channel =
(
    SELECT channel
    FROM marketing_data
    GROUP BY channel
    ORDER BY SUM(sales_revenue) DESC
    LIMIT 1
);

## Q4:- Show campaigns from regions whose average revenue exceeds ₹60,000.

SELECT *
FROM marketing_data
WHERE region IN
(
    SELECT region
    FROM marketing_data
    GROUP BY region
    HAVING AVG(sales_revenue) > 60000
);

## Q5:- Find campaigns that performed better than the average campaign in their own region.

SELECT
    id,
    region,
    sales_revenue
FROM marketing_data m1
WHERE sales_revenue >
(
    SELECT AVG(sales_revenue)
    FROM marketing_data m2
    WHERE m1.region = m2.region
);


## Q6:- Create a reusable table showing total revenue by channel.

WITH ChannelRevenue AS
(
    SELECT
        channel,
        SUM(sales_revenue) AS Total_Revenue
    FROM marketing_data
    GROUP BY channel
)

SELECT *
FROM ChannelRevenue
ORDER BY Total_Revenue DESC;


## Q7:- Which channels generated above-average total revenue?

WITH ChannelRevenue AS
(
    SELECT
        channel,
        SUM(sales_revenue) AS Total_Revenue
    FROM marketing_data
    GROUP BY channel
)

SELECT *
FROM ChannelRevenue
WHERE Total_Revenue >
(
    SELECT AVG(Total_Revenue)
    FROM ChannelRevenue
);

## Q8:- Rank regions based on total sales revenue using a CTE.


WITH RegionRevenue AS
(
    SELECT
        region,
        SUM(sales_revenue) AS Total_Revenue
    FROM marketing_data
    GROUP BY region
)

SELECT *
FROM RegionRevenue
ORDER BY Total_Revenue DESC;


## Q9:- Find campaigns whose revenue is above the average revenue of their marketing channel using a CTE.

WITH ChannelAverage AS
(
    SELECT
        channel,
        AVG(sales_revenue) AS Avg_Revenue
    FROM marketing_data
    GROUP BY channel
)

SELECT
    m.id,
    m.channel,
    m.sales_revenue
FROM marketing_data m
JOIN ChannelAverage c
ON m.channel = c.channel
WHERE m.sales_revenue > c.Avg_Revenue;

## Q10:- Create an executive summary showing total campaigns and total revenue by customer segment.


WITH SegmentSummary AS
(
    SELECT
        customer_segment,
        COUNT(*) AS Total_Campaigns,
        SUM(sales_revenue) AS Total_Revenue
    FROM marketing_data
    GROUP BY customer_segment
)

SELECT *
FROM SegmentSummary
ORDER BY Total_Revenue DESC;


                                  ## MODULE 5
   
   ## Q1:- Assign a serial number to campaigns based on revenue (highest first).

   SELECT
    id,
    sales_revenue,
    ROW_NUMBER() OVER (
        ORDER BY sales_revenue DESC
    ) AS Revenue_Rank
FROM marketing_data;

## Q2:- Rank campaigns by revenue while allowing ties.

SELECT
    id,
    sales_revenue,
    RANK() OVER (
        ORDER BY sales_revenue DESC
    ) AS Revenue_Rank
FROM marketing_data;

## Q3:- Find the top-performing campaign in each region.

SELECT *
FROM
(
    SELECT
        id,
        region,
        sales_revenue,
        ROW_NUMBER() OVER (
            PARTITION BY region
            ORDER BY sales_revenue DESC
        ) AS rn
    FROM marketing_data
) t
WHERE rn = 1;


## Q4:- What was the previous campaign's revenue?

SELECT
    id,
    date,
    sales_revenue,
    LAG(sales_revenue) OVER (
        ORDER BY date
    ) AS Previous_Revenue
FROM marketing_data;

## Q5:- What is the next campaign's revenue?

SELECT
    id,
    date,
    sales_revenue,
    LEAD(sales_revenue) OVER (
        ORDER BY date
    ) AS Next_Revenue
FROM marketing_data;

## Q6:- Calculate the running total of sales revenue over time.

SELECT
    date,
    sales_revenue,
    SUM(sales_revenue) OVER (
        ORDER BY date
    ) AS Running_Total
FROM marketing_data;


## Q7:- Calculate the average revenue for each region without losing campaign-level detail.

SELECT
    id,
    region,
    sales_revenue,
    AVG(sales_revenue) OVER (
        PARTITION BY region
    ) AS Region_Average
FROM marketing_data;

## Q8:- Compare each campaign's revenue with the highest revenue in its region.

SELECT
    id,
    region,
    sales_revenue,
    MAX(sales_revenue) OVER (
        PARTITION BY region
    ) AS Highest_Regional_Revenue
FROM marketing_data;


## Q9:- Display the top three campaigns in each region.

SELECT *
FROM
(
    SELECT
        id,
        region,
        sales_revenue,
        DENSE_RANK() OVER (
            PARTITION BY region
            ORDER BY sales_revenue DESC
        ) AS Rank_No
    FROM marketing_data
) t
WHERE Rank_No <= 3;

                                       ## MODULE 6


## Q1:- Create a reusable report showing revenue by marketing channel.

CREATE VIEW vw_channel_revenue AS
SELECT
    channel,
    SUM(sales_revenue) AS Total_Revenue
FROM marketing_data
GROUP BY channel;

SELECT *
FROM vw_channel_revenue;


## Q2:- Create a reusable report showing average revenue by region.

CREATE VIEW vw_region_performance AS
SELECT
    region,
    AVG(sales_revenue) AS Avg_Revenue
FROM marketing_data
GROUP BY region;

SELECT *
FROM vw_region_performance;

## Q3:- Modify the regional performance view to also include the total number of campaigns.

CREATE OR REPLACE VIEW vw_region_performance AS
SELECT
    region,
    COUNT(*) AS Total_Campaigns,
    AVG(sales_revenue) AS Avg_Revenue
FROM marketing_data
GROUP BY region;


## Q4:- The marketing team frequently searches campaigns by region. Improve query performance.

CREATE INDEX idx_region
ON marketing_data(region);

SELECT *
FROM marketing_data
WHERE region = 'North';

## Q5:- Analysts often filter by both region and channel. Optimize these queries.

CREATE INDEX idx_region_channel
ON marketing_data(region, channel);

SELECT *
FROM marketing_data
WHERE region = 'North'
  AND channel = 'Email';
  
                                          ## MODULE 7


## Q1:- Display all marketing channels in uppercase for a standardized report.

SELECT
    channel,
    UPPER(channel) AS Channel_Uppercase
FROM marketing_data;


## Q2:- Display customer segments in lowercase.

SELECT
    customer_segment,
    LOWER(customer_segment) AS Segment_Lower
FROM marketing_data;

## Q3:- Create a descriptive campaign label by combining region and channel.

SELECT
    CONCAT(region, ' - ', channel) AS Campaign_Label
FROM marketing_data;

## Q4:- How many characters are in each product category name?

SELECT
    product_category,
    LENGTH(product_category) AS Name_Length
FROM marketing_data;

## Q5:- In which year was each campaign conducted?

SELECT
    date,
    YEAR(date) AS Campaign_Year
FROM marketing_data;


## Q6:- Which month was each campaign launched?

SELECT
    date,
    MONTH(date) AS Campaign_Month
FROM marketing_data;

## Q7:- Display the month name instead of the month number.

SELECT
    date,
    MONTHNAME(date) AS Month_Name
FROM marketing_data;

## Q8:-  How many days have passed since each campaign was launched?

SELECT
    id,
    date,
    DATEDIFF(CURDATE(), date) AS Days_Since_Campaign
FROM marketing_data;

## Q9:- Round sales revenue to the nearest whole number.

SELECT
    sales_revenue,
    ROUND(sales_revenue, 0) AS Rounded_Revenue
FROM marketing_data;

## Q10:- Calculate the average sales revenue rounded to two decimal places.

SELECT
    ROUND(AVG(sales_revenue), 2) AS Average_Revenue
FROM marketing_data;

## Q11:- If competition_index is NULL, display 0 instead.

SELECT
    competition_index,
    IFNULL(competition_index, 0) AS Competition_Index
FROM marketing_data;

## Q12:- Display the first non-NULL value between competition_index and seasonality_index.

SELECT
    COALESCE(competition_index, seasonality_index) AS Business_Index
FROM marketing_data;

## Q13:- Create a monthly Revenue REport?

SELECT
    YEAR(date) AS Year,
    MONTHNAME(date) AS Month,
    SUM(sales_revenue) AS Total_Revenue
FROM marketing_data
GROUP BY
    YEAR(date),
    MONTH(date),
    MONTHNAME(date)
ORDER BY
    Year,
    MONTH(date);
    
                                ## MODULE 8
  
## Q1:- Which marketing channel generated the highest total revenue?**

SELECT
    channel,
    SUM(sales_revenue) AS Total_Revenue
FROM marketing_data
GROUP BY channel
ORDER BY Total_Revenue DESC
LIMIT 1;


## Q2: Which marketing channel generated the highest Return on Investment (ROI)?

SELECT
    channel,
    SUM(sales_revenue) AS Revenue,
    SUM(ad_spend) AS Ad_Spend,
    ROUND(
        ((SUM(sales_revenue) - SUM(ad_spend))
        / SUM(ad_spend)) * 100,2
    ) AS ROI_Percentage
FROM marketing_data
GROUP BY channel
ORDER BY ROI_Percentage DESC;

## Q3:- Which region generated the highest total revenue?

SELECT
    region,
    SUM(sales_revenue) AS Total_Revenue
FROM marketing_data
GROUP BY region
ORDER BY Total_Revenue DESC;

## Q4:- Which five campaigns generated the highest revenue?

SELECT
    id,
    channel,
    region,
    sales_revenue
FROM marketing_data
ORDER BY sales_revenue DESC
LIMIT 5;

## Q5:-What percentage of total revenue does each channel contribute?**

SELECT
    channel,
    SUM(sales_revenue) AS Revenue,
    ROUND(
        SUM(sales_revenue) * 100 /
        (SELECT SUM(sales_revenue)
         FROM marketing_data),
        2
    ) AS Revenue_Percentage
FROM marketing_data
GROUP BY channel
ORDER BY Revenue_Percentage DESC;


## Q5:- Which campaigns performed above the average revenue?

SELECT
    id,
    channel,
    sales_revenue
FROM marketing_data
WHERE sales_revenue >
(
    SELECT AVG(sales_revenue)
    FROM marketing_data
);


## Q6:-Which customer segment generates the highest Customer Lifetime Value?**

SELECT
    customer_segment,
    AVG(customer_lifetime_value) AS Average_CLV
FROM marketing_data
GROUP BY customer_segment
ORDER BY Average_CLV DESC;


## Q7:- Identify the top three campaigns in every region.

SELECT *
FROM
(
    SELECT
        id,
        region,
        sales_revenue,
        DENSE_RANK() OVER(
            PARTITION BY region
            ORDER BY sales_revenue DESC
        ) AS Rank_No
    FROM marketing_data
) t
WHERE Rank_No <= 3;


## Q8:- How has revenue changed month by month?

SELECT
    YEAR(date) AS Year,
    MONTHNAME(date) AS Month,
    SUM(sales_revenue) AS Total_Revenue
FROM marketing_data
GROUP BY
    YEAR(date),
    MONTH(date),
    MONTHNAME(date)
ORDER BY
    Year,
    MONTH(date);

## Q9:- Classify campaigns into High, Medium, and Low performers.


SELECT
    id,
    sales_revenue,
    CASE
        WHEN sales_revenue >= 80000 THEN 'High'
        WHEN sales_revenue >= 50000 THEN 'Medium'
        ELSE 'Low'
    END AS Performance_Category
FROM marketing_data;




